### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by gertvdijk** [sphinx-contrib/domaintools#1]
It seems this extension does not run if running Sphinx with Python 3, due to (at least) the use of `iteritems()`:

https://github.com/sphinx-contrib/domaintools/blob/eb19a11a7d07af0cf20913290f55b8f07063b2cb/sphinxcontrib/domaintools.py#L129

**Comment by tk0miya** [comment]
Fixed by #2.
Thank you for reporting.
